name: Build and deploy JAR app to Azure Web App - GestionCitas1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 Cambia de read a write (para evitar el error git 128)
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 👈 Esto evita errores de git shallow clone

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests   # 👈 "package" es más correcto que "install" para generar el .jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar   # 👈 Sin variables extra ni comillas innecesarias

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8EEDE5653D174522816F2677E483F4B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_42BD941A4ED34CD395C0373C328B0EC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_504438BC3001421292DFD4854FA26020 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GestionCitas1'
          slot-name: 'Production'
          package: '*.jar'

          
